---
- hosts: all
  tasks:
    - name: |
        Install
        tmux
        docker
        docker-compose
        ufw
        nnn
        borgbackup
      apt:
        name: |
          tmux
          ,docker
          ,docker-compose
          ,ufw
          ,nnn
          ,borgbackup
        update_cache: yes
