---
- hosts: all
  tasks:
    - name: Fail if variable username is not specified
      fail:
        msg: "You must specify the username variable (ex. with -e username=<name>)."
      when: username is not defined

    - name: Install zsh
      apt:
        name: zsh

    - name: Add a docker group
      ansible.builtin.group:
        name: docker

    - name: Add a group for the specified username
      ansible.builtin.group:
        name: '{{ username }}'

    - name: Add a user of the specified username {{ username }} in the groups {{ username }},sudo,docker with zsh as default shell.
      ansible.builtin.user:
        name: '{{ username }}'
        groups: '{{ username }},sudo,docker'
        shell: /usr/bin/zsh

    - import_playbook: user_dotfiles.yml
